apiVersion: cloudidentity.cnrm.cloud.google.com/v1beta1
kind: CloudIdentityGroup
metadata:
  name: cloudidentitygroup
spec:
  displayName: Cloud Identity Group Name
  description: This is a test CloudIdentityGroup. It should be modified before use as a sample.
  groupKey:
    id: {{ .Values.cloudIdentityGroup.groupKey }}
  parent: customers/{{ .Values.cloudIdentityGroup.customerId }}
  labels:
    cloudidentity.googleapis.com/groups.discussion_forum: ""
