apiVersion: cloudidentity.cnrm.cloud.google.com/v1beta1
kind: CloudIdentityMembership
metadata:
  name: cloudidentitymembership
spec:
  groupRef:
    name: cloudidentitygroup
  preferredMemberKey:
    id: {{ .Values.cloudIdentityMembership.memberKey }}
  roles:
  - name: MEMBER
    expiryDetail:
      expireTime: 2222-10-02T15:01:23Z
