apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember
spec:
  member: {{ .Values.iamPolicy.member }}
  role: {{ .Values.iamPolicy.role }}
  condition:
      title: expires_after_2019_12_31
      description: Expires at midnight of 2019-12-31
      expression: request.time < timestamp("2020-01-01T00:00:00Z")
  resourceRef:
      kind: Project
      external: projects/{{ .Values.projectId }}
